import { NextResponse } from 'next/server';
import { ActionType, Instance, ProcessStatus, Role } from '@/lib/constants';
import { getAuth } from '@/lib/auth'; import { prisma } from '@/lib/prisma'; import { canAct } from '@/lib/access'; import { defenseDeadline } from '@/lib/deadlines';
export async function POST(req:Request,{params}:{params:{id:string}}){const s=await getAuth();if(!s)return NextResponse.json({error:'Não autorizado'},{status:401});const b=await req.json();const p=await prisma.process.findUnique({where:{id:params.id},include:{participants:true}});if(!p)return NextResponse.json({error:'Processo não encontrado'},{status:404});
if(b.action==='assumir'){const valid=(s.user.role===Role.JUIZ&&p.instance===Instance.PRIMEIRA)||(s.user.role===Role.DESEMBARGADOR&&p.instance===Instance.SEGUNDA)||s.user.role===Role.ADMIN;if(!valid)return NextResponse.json({error:'Seu cargo não pode assumir esta instância.'},{status:403});const result=await prisma.process.updateMany({where:{id:p.id,assignedToId:null,status:{in:[ProcessStatus.AGUARDANDO_JUIZ,ProcessStatus.AGUARDANDO_DESEMBARGADOR]}},data:{assignedToId:s.user.id,status:ProcessStatus.EM_ANALISE}});if(!result.count)return NextResponse.json({error:'Este processo já foi assumido.'},{status:409});await prisma.processAction.create({data:{processId:p.id,userId:s.user.id,type:ActionType.ASSUMIDO,note:'Processo assumido para análise.'}});return NextResponse.json({ok:true});}
if(b.action==='assumir_oficial'){if(s.user.role!==Role.OFICIAL_JUSTICA)return NextResponse.json({error:'Somente Oficial de Justiça pode assumir a intimação.'},{status:403});const result=await prisma.process.updateMany({where:{id:p.id,officerId:null,status:ProcessStatus.AGUARDANDO_INTIMACAO},data:{officerId:s.user.id,officerDueAt:new Date(Date.now()+3*86400000),status:ProcessStatus.EM_INTIMACAO}});if(!result.count)return NextResponse.json({error:'Esta intimação já foi assumida.'},{status:409});await prisma.processAction.create({data:{processId:p.id,userId:s.user.id,type:ActionType.ASSUMIDO,note:'Oficial de Justiça assumiu a intimação. Prazo de entrega: 3 dias.'}});return NextResponse.json({ok:true});}
const defenseCanAct=s.user.role===Role.ADVOGADO&&p.participants.some(x=>x.userId===s.user.id&&x.role===Role.ADVOGADO);
if(b.action==='defesa'){if(!defenseCanAct||p.status!==ProcessStatus.AGUARDANDO_DEFESA)return NextResponse.json({error:'A defesa não pode se manifestar nesta fase.'},{status:403});await prisma.$transaction([prisma.process.update({where:{id:p.id},data:{status:ProcessStatus.DEFESA_APRESENTADA}}),prisma.processAction.create({data:{processId:p.id,userId:s.user.id,type:ActionType.DEFESA_APRESENTADA,note:b.note?.trim()||'Defesa apresentada dentro do prazo.'}})]);return NextResponse.json({ok:true});}
if(b.action==='solicitar_segunda'){if(!defenseCanAct)return NextResponse.json({error:'Somente a defesa vinculada pode solicitar a 2ª instância.'},{status:403});await prisma.$transaction([prisma.process.update({where:{id:p.id},data:{status:ProcessStatus.AGUARDANDO_DESEMBARGADOR,instance:Instance.SEGUNDA,assignedToId:null}}),prisma.processAction.create({data:{processId:p.id,userId:s.user.id,type:ActionType.ENVIADO_SEGUNDA_INSTANCIA,note:b.note?.trim()||'2ª instância solicitada pela defesa.'}})]);return NextResponse.json({ok:true});}
if(b.action==='pausar'||b.action==='retomar'){if(s.user.role!==Role.ADMIN)return NextResponse.json({error:'Somente a administração pode pausar ou retomar processos.'},{status:403});const pause=b.action==='pausar';if(pause&&p.status===ProcessStatus.PAUSADO)return NextResponse.json({error:'O processo já está pausado.'},{status:400});if(!pause&&p.status!==ProcessStatus.PAUSADO)return NextResponse.json({error:'O processo não está pausado.'},{status:400});await prisma.$transaction([prisma.process.update({where:{id:p.id},data:pause?{pausedStatus:p.status,status:ProcessStatus.PAUSADO}:{status:p.pausedStatus||ProcessStatus.EM_ANALISE,pausedStatus:null}}),prisma.processAction.create({data:{processId:p.id,userId:s.user.id,type:pause?ActionType.PAUSADO:ActionType.RETOMADO,note:b.note?.trim()||(pause?'Processo pausado pela administração.':'Processo retomado pela administração.')}})]);return NextResponse.json({ok:true});}
if(!canAct(p,s))return NextResponse.json({error:'Somente quem assumiu o processo pode realizar esta ação.'},{status:403});
if(b.action==='instrucao'){await prisma.$transaction([prisma.process.update({where:{id:p.id},data:{status:ProcessStatus.AGUARDANDO_INTIMACAO,defenseDueAt:null}}),prisma.processAction.create({data:{processId:p.id,userId:s.user.id,type:ActionType.INSTRUCAO,note:'Instrução iniciada e encaminhada para intimação pelo Oficial de Justiça.'}})]);return NextResponse.json({ok:true});}
if(b.action==='prorrogar'){if(p.status!==ProcessStatus.AGUARDANDO_DEFESA||p.defenseExtensionDays>=2)return NextResponse.json({error:'A prorrogação só pode totalizar até 2 dias durante a instrução.'},{status:400});const extra=Math.min(2-p.defenseExtensionDays,Math.max(1,Number(b.days)||1));await prisma.$transaction([prisma.process.update({where:{id:p.id},data:{defenseExtensionDays:{increment:extra},defenseDueAt:new Date((p.defenseDueAt||new Date()).getTime()+extra*86_400_000)}}),prisma.processAction.create({data:{processId:p.id,userId:s.user.id,type:ActionType.PRAZO_PRORROGADO,note:`Prazo da defesa prorrogado por ${extra} dia(s).`}})]);return NextResponse.json({ok:true});}
if(b.action==='audiencia'){const date=new Date(b.hearingAt);if(Number.isNaN(date.getTime()))return NextResponse.json({error:'Informe uma data válida.'},{status:400});await prisma.$transaction([prisma.process.update({where:{id:p.id},data:{hearingAt:date}}),prisma.processAction.create({data:{processId:p.id,userId:s.user.id,type:ActionType.AUDIENCIA_AGENDADA,note:`Audiência agendada para ${date.toLocaleString('pt-BR')}.`}})]);return NextResponse.json({ok:true});}
const map:Record<string,[string,string]>={autorizar:[ProcessStatus.AUTORIZADO,ActionType.AUTORIZADO],devolver:[ProcessStatus.DEVOLVIDO,ActionType.DEVOLVIDO],negar:[ProcessStatus.NEGADO,ActionType.NEGADO],decidir:[ProcessStatus.FINALIZADO,ActionType.AUTORIZADO]};const found=map[b.action];if(!found)return NextResponse.json({error:'Ação inválida'},{status:400});
const name=String(b.actorName||'').trim(),identifier=String(b.actorId||'').trim(),note=String(b.note||'').trim();const document=b.document;
if(!name||!identifier)return NextResponse.json({error:'Informe seu nome e ID para registrar a decisão.'},{status:400});
if(!document?.path?.startsWith('/uploads/')||document.mimeType!=='application/pdf')return NextResponse.json({error:'Anexe o documento da decisão em PDF.'},{status:400});
if(b.action==='devolver'&&!note)return NextResponse.json({error:'Informe o motivo do ajuste solicitado.'},{status:400});
const record=`Decisão registrada por ${name} (ID ${identifier}).${note?` ${note}`:''}`;
await prisma.$transaction([prisma.process.update({where:{id:p.id},data:{status:found[0],decisionAt:b.action==='decidir'?new Date():p.decisionAt}}),prisma.attachment.create({data:{processId:p.id,name:document.name||'Documento da decisão.pdf',path:document.path,mimeType:'application/pdf'}}),prisma.processAction.create({data:{processId:p.id,userId:s.user.id,type:found[1],note:record}})]);return NextResponse.json({ok:true});}
