export const Role = { ADMIN:'ADMIN', PROMOTOR:'PROMOTOR', JUIZ:'JUIZ', DESEMBARGADOR:'DESEMBARGADOR', ADVOGADO:'ADVOGADO', VITIMA:'VITIMA' } as const;
export type Role = typeof Role[keyof typeof Role];
export const ProcessStatus = { RASCUNHO:'RASCUNHO', AGUARDANDO_JUIZ:'AGUARDANDO_JUIZ', EM_ANALISE:'EM_ANALISE', INSTRUCAO:'INSTRUCAO', AGUARDANDO_DEFESA:'AGUARDANDO_DEFESA', DEFESA_APRESENTADA:'DEFESA_APRESENTADA', DECISAO:'DECISAO', DEVOLVIDO:'DEVOLVIDO', AUTORIZADO:'AUTORIZADO', NEGADO:'NEGADO', SEGUNDA_INSTANCIA:'SEGUNDA_INSTANCIA', AGUARDANDO_DESEMBARGADOR:'AGUARDANDO_DESEMBARGADOR', FINALIZADO:'FINALIZADO' } as const;
export type ProcessStatus = typeof ProcessStatus[keyof typeof ProcessStatus];
export const Instance = { PRIMEIRA:'PRIMEIRA', SEGUNDA:'SEGUNDA' } as const;
export const ActionType = { CRIADO:'CRIADO', ENVIADO:'ENVIADO', ASSUMIDO:'ASSUMIDO', INSTRUCAO:'INSTRUCAO', DEFESA_APRESENTADA:'DEFESA_APRESENTADA', PRAZO_PRORROGADO:'PRAZO_PRORROGADO', AUDIENCIA_AGENDADA:'AUDIENCIA_AGENDADA', DECISAO_AUTOMATICA:'DECISAO_AUTOMATICA', AUTORIZADO:'AUTORIZADO', DEVOLVIDO:'DEVOLVIDO', NEGADO:'NEGADO', PARTICIPANTE_ADICIONADO:'PARTICIPANTE_ADICIONADO', ARQUIVO_ANEXADO:'ARQUIVO_ANEXADO', ENVIADO_SEGUNDA_INSTANCIA:'ENVIADO_SEGUNDA_INSTANCIA', COMENTARIO:'COMENTARIO' } as const;
export type ActionType = typeof ActionType[keyof typeof ActionType];
