export type Crime={article:string;name:string;level:number;value:number};
const groups:[number,string,string[]][]=[
[1,'1.000.000',['21|Adultério','22|Bigamia','55|Desobediência','61|Perturbação da Ordem','65|Alta Velocidade','67|Corridas Ilegais','69|Poluição Sonora','70|Veículo Muito Danificado','71|Veículo Ilegalmente Estacionado','72|Uso Excessivo de Insulfilm','75|Uso de Colete (Roupa)']],
[2,'2.000.000',['3|Desacato','4|Impedir Exercício Profissional','14|Assédio Moral','15|Calúnia','16|Difamação','17|Injúria','37|Posse de Peças de Armas','38|Posse de Cápsula','43|Porte de Arma Branca','62|QRR Ilegal','63|Tentativa de Fuga','66|Condução Imprudente','68|Dirigir na Contramão','74|Uso de Coldre']],
[3,'3.000.000',['1|Abuso de Autoridade','5|Prevaricação','6|Prisão Disciplinar','18|Importunação Sexual','30|Dano à Propriedade do Governo','35|Posse de Produtos Ilegais','46|Posse de Componentes Narcóticos','52|Apologia ao Crime','53|Falsidade Ideológica','60|Omissão de Socorro','73|Ocultação Facial']],
[4,'4.000.000',['2|Corrupção Passiva/Ativa','7|Tráfico de Influência','8|Uso Irregular de Função Pública','19|Perjúrio','31|Estelionato','36|Tráfico de Produtos Ilegais','39|Porte de Arma Leve','44|Posse de Munição (1–100)','47|Posse de Drogas (6–100)','49|Dinheiro Sujo Leve','56|Exercício Ilegal de Profissão','57|Falsa Comunicação de Crime','59|Ocultação de Provas','76|Porte de Colete Balístico']],
[5,'5.000.000',['24|Ameaça','25|Extorsão','26|Lesão Corporal','29|Vandalismo','32|Invasão de Propriedade','41|Porte de Arma Pesada','45|Tráfico de Munição (+100)','48|Tráfico de Drogas (+100)','50|Dinheiro Sujo Médio','64|Tentativa de Suborno','77|Tráfico de Colete Balístico']],
[6,'6.000.000',['10|Homicídio Culposo','20|Abandono de Incapaz','27|Sequestro','33|Furto','40|Tráfico de Armas Leve','51|Dinheiro Sujo Grave','54|Formação de Quadrilha','58|Obstrução de Justiça']],
[7,'7.000.000',['9|Tentativa de Homicídio','11|Homicídio Doloso','12|Homicídio Qualificado','13|Latrocínio','23|Crime Sexual Intrafamiliar','28|Tortura','34|Roubo','42|Tráfico de Armas Pesada']]
];
export const crimes:Crime[]=groups.flatMap(([level,raw,items])=>items.map(item=>{const[article,name]=item.split('|');return{article:`Art. ${article}`,name,level:Number(level),value:Number(String(raw).replace(/\./g,''))}}));
export function calculateIndemnity(selected:string[],assets:number,defendants:number){const found=selected.map(key=>crimes.find(c=>`${c.article} — ${c.name}`===key)).filter(Boolean) as Crime[];const occurrences:Record<number,number>={};let total=0;for(const c of found){const count=occurrences[c.level]||0;total+=c.value*(count?0.2:1);occurrences[c.level]=count+1}const cap=Math.min(20_000_000,assets>0?assets*.25:20_000_000);total=Math.min(total,cap);return{total,promoter:total*.15,magistrate:total*.10,victims:total*.75,perDefendant:defendants?total/defendants:total}}
