'use client';
import { motion } from 'framer-motion'; import { signIn } from 'next-auth/react'; import { useState } from 'react';
const roles = [
  ['PROMOTOR', 'Promotor'], ['JUIZ', 'Juiz'], ['DESEMBARGADOR', 'Desembargador'], ['ADVOGADO', 'Advogado de Defesa'], ['VITIMA', 'Vítima']
];

export default function Login(){
  const [mode,setMode]=useState<'login'|'register'>('login'); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [busy,setBusy]=useState(false);
  async function submitLogin(f:FormData){setBusy(true);setError('');const r=await signIn('credentials',{numericId:f.get('id'),name:f.get('name'),password:f.get('password'),redirect:false});setBusy(false);if(r?.error)setError('Dados de acesso inválidos.');else location.href='/dashboard'}
  async function submitRegister(f:FormData){setBusy(true);setError('');setSuccess('');const r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});const data=await r.json();setBusy(false);if(!r.ok){setError(data.error||'Não foi possível concluir o cadastro.');return;}setSuccess('Cadastro concluído. Entre com seu CPF ou e-mail e sua senha.');setMode('login');}
  return <main className="grid min-h-screen place-items-center p-5"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="panel w-full max-w-md p-8 shadow-glow"><div className="mb-7 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-lg bg-red-700 text-xl">⚖</div><div><h1 className="text-xl font-semibold">Portal Jurídico</h1><p className="text-sm text-slate-400">Acesso individual e protegido</p></div></div><div className="mb-6 grid grid-cols-2 gap-2 rounded-lg bg-[#091426] p-1"><button type="button" onClick={()=>{setMode('login');setError('')}} className={mode==='login'?'btn':'btn-outline'}>Entrar</button><button type="button" onClick={()=>{setMode('register');setError('')}} className={mode==='register'?'btn':'btn-outline'}>Cadastrar</button></div>{mode==='login'?<form onSubmit={e=>{e.preventDefault();submitLogin(new FormData(e.currentTarget))}}><label className="mb-4 block text-sm">CPF ou e-mail<input name="id" required className="input mt-1" placeholder="CPF ou nome@exemplo.com"/></label><label className="mb-4 block text-sm">Nome completo <span className="text-slate-500">(exceto administrador)</span><input name="name" className="input mt-1" placeholder="Seu nome"/></label><label className="mb-5 block text-sm">Senha<input name="password" type="password" required className="input mt-1"/></label>{error&&<p className="mb-4 text-sm text-red-400">{error}</p>}{success&&<p className="mb-4 text-sm text-green-400">{success}</p>}<button disabled={busy} className="btn w-full">{busy?'Entrando…':'Entrar no sistema'}</button></form>:<form onSubmit={e=>{e.preventDefault();submitRegister(new FormData(e.currentTarget))}}><label className="mb-3 block text-sm">Nome completo<input name="name" required minLength={3} className="input mt-1" placeholder="Seu nome"/></label><label className="mb-3 block text-sm">CPF<input name="cpf" required inputMode="numeric" className="input mt-1" placeholder="Somente números"/></label><label className="mb-3 block text-sm">Cargo<select name="role" required className="input mt-1">{roles.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="mb-3 block text-sm">E-mail<input name="email" required type="email" className="input mt-1" placeholder="nome@exemplo.com"/></label><label className="mb-5 block text-sm">Criar senha<input name="password" required minLength={8} type="password" className="input mt-1" placeholder="Mínimo de 8 caracteres"/></label>{error&&<p className="mb-4 text-sm text-red-400">{error}</p>}<button disabled={busy} className="btn w-full">{busy?'Cadastrando…':'Criar cadastro'}</button></form>}<p className="mt-5 text-center text-xs text-slate-500">Login único • sessão protegida • ações registradas</p></motion.div></main>}
